language: java
install: true
script:
- mvn clean package
services:
- docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push.sh
env:
  global:
  - secure: Z9IorU7zeqM5ZYTXVcnGDa639JWxxn/gsQElXSrQ8A06psIh9v45C1rgDjAHrI1TVMxXGLm7ATewSNHdzBtzyC4aqodVDrD1R49lHih9A70kTfhubgL8ZSurgH8l6Yc9X6bfb/BI4rBh9LBPzXaeicXde2owBgCUWgmMcsaX/4HwO4Jt0AyRHtN/lZ0VcoEKyzmm47JdmLPxjn2TvYMO40Q8tFIb+SdJv9IwexUsLF2l267xZrCTien2m+rxQ+mwoQN/k8+j/Yaa8ujsKmatfGNNnZFNg63Y3psyUoKLGBIqDlsJElE7Ioy39JeXT96rMO05Rhda7S08tXMOlNzMONHZns6+b181wfJqsxVN+S0Dff4DXbtrm9z/UZGSqkcl+jfC7LRBal8psHK/uIvTC9LknMUu4n3e6beWlWmw6/3USFHgPmdPKl5PHrXK/2S1w2iNeb20q6LuT2eIwv4VX2WEgt8XlAkyxzOphYZNM34K0kH7O4VSnKmsVOvnB68OMGv23uNvwpov6ZDC3y0igRChGWVcyuZnyEAoPPoBflMPy2Bq4iT53TuPTrVWxSjDTIH+JTI4LUn6eAuMIx4R0wz3wsE9I3g9+cY/OGdIxrRqNB+2giW16PUiVTuf3KOrYmRBYJtLlM5ySJ7qeDg2r1RDFgjXKTwiVSWCNebyMh4=
  - secure: dKoG+Z4i4x9Tm/pj+CqM1LNwjsYQllin5qYA6aA1sVG33DZjCK81otkSte/d9Y9yC5hlkda2biwWlX/mP1UUMz6Txmp+CHZR6Zt5zpvdmHC5u7Zu9zrw1z8NSHCYNrjcJe4S/Z9+B+iqQeLFx2R7mPImWrpDP7hN1VjxMtQlgZsOEtGK/WlHo+74VuR6L4h301wadxfcQv8wiYrAUEdrv5NcodPHKmQvq4Zk15vuU2FYtI6rtODiQBPUtmyQJdlVPIH3YaRW5A+YdnZXCPQ8PGKt/aRScfczhoEzEeNvsKXY4+IGZ5kav3WpApjUCZwftquqSHdFcBrmklqUpB7L/ph+Ivg2ZkP86zITYgsnN8UPVGb0dsjujmQN14E0DU/ZfAFIPRgkfGggn8hh3byoJHpN/+Y/2WyWOVzmUG7JV8wv/PcVW54rtcGRaE4DFPKf51thG3m7ZbIYlNFyfDsInw8W6hgDWPG3gYL+KTkpObcEDJO9eHkPOY7z4V2RxHfF2ulesF59/j01ZP7P3FZoSQI4JEgmOqXBA5drGDkDQLseTbYuYVsd01Fkfc07ZJjrTJQhkRhAggTEk5+JkTAo/RhPh14fHaZdNrZVygo83+04LZEMT0XYBCdiZrRLmB9TAk6JcP1XA4pY0zZpGJAZdw/h4GcsXKkF1YKgnG/XvRA=

