spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    continue-on-error: true
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
      path: /h2